languageCode = 'en-us'
title = 'PWA Conference'
uglyurls = true
baseURL = "https://mercypl0x.github.io/conference/"
relativeURLs = false
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[menu]

[[menu.main]]
  name = 'Programme'
  identifier = 'day'
  url = 'day/'
  weight = 10

[[menu.main]]
  name = 'Speakers'
  identifier = 'speaker'
  url = 'speaker/'
  weight = 20

  
[[menu.main]]
  name = 'Team'
  identifier = 'person'
  url = 'person/'
  weight = 40
  
[[menu.main]]
  name = 'Sponsors'
  identifier = 'sponsor'
  url = 'sponsor/'
  weight = 50

  [[menu.main]]
  name = 'Venues'
  identifier = 'venue'
  url = 'venue/'
  weight = 30

